'\" t
.\"     Title: \e20\e4\e8nc
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/05/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "\E20\E4\E8NC" "1" "12/05/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
2048nc \- The game 2048 for your Linux terminal
.SH "SYNOPSIS"
.sp
\fB2048nc\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
A non\-ncurses cli version of the game 2048 for your Linux terminal\&.
.SH "OPTIONS"
.PP
\fB\-s\fR \fIsize\fR
.RS 4
Set the grid border length to
\fIsize\fR\&.
.RE
.PP
\fB\-b\fR \fIrate\fR
.RS 4
Set the block spawn rate to
\fIrate\fR\&.
.RE
.PP
\fB\-r\fR
.RS 4
Resets hiscore\&. Will prompt user\&.
.RE
.PP
\fB\-h\fR
.RS 4
Display usage information\&.
.RE
.SH "CONTROLS"
.PP
\fBhjkl\fR or \fBwasd\fR
.RS 4
Movement
.RE
.PP
\fBq\fR
.RS 4
Quit the game\&.
.RE
.SH "AUTHOR"
.sp
2048nc was originally written by Thiehuis\&. Some people have contributed to it\&.
.sp
This manpage is Copyright (C) 2014 Björn Esser and licensed under the terms of the MIT License (MIT)\&.
.SH "RESOURCES"
.sp
github: https://github\&.com/Tiehuis/2048\-cli/
.SH "COPYING"
.sp
Copyright (C) 2014 Tiehuis\&. Free use of this software is granted under the terms of the MIT License (MIT)\&.
