.TH 2048 1

.SH NAME
2048 \- play the game 2048 in your terminal

.SH SYNOPSIS
.B 2048
[\fB\-hrcCaA\fR]
[\fB\-s\fR \fISIZE\fR]
[\fB\-b\fR \fIRATE\fR]

.SH DESCRIPTION
.B 2048
is an implementation of the popular game, 2048, designed to be run on a
terminal. It is designed to be easy to understand and extend.

.SH CONTROLS
.TP
.BR hjkl " " and " " wasd
Default movement keys. Depending on the graphics implementation, there may be
extra alternatives.
.TP
.BR \q
Quit the current game.

.SH OPTIONS
.TP
.BR \-h
Print the program usage.
.TP
.BR \-H
Print the current highscore.
.TP
.BR \-c
Enable color support if supported.
.TP
.BR \-C
Disable color support (default).
.TP
.BR \-a
Enable animations (default).
.TP
.BR \-A
Disable animations.
.TP
.BR \-i
Enable ai without displaying game.
.TP
.BR \-I
Enable ai and display game.
.TP
.BR \-r
Reset highscore. Will prompt user.
.TP
.BR \-s " " \fISIZE\fR
Set the size of the playing field. Default is 4. Maximum value is 16, minimum is 4.
.TP
.BR \-b " " \fIRATE\fR
Set the rate at which blocks are spawned. Default is 1.

.SH AUTHORS
Originally written by Marc Tiehuis.
All contributions can be found at \fIhttps://github.com/Tiehuis/2048-cli\fR.

.SH COPYRIGHT
MIT License (2014)
